const SET_LIST = 'SET_LIST'
const GET_LIST = 'GET_LIST'
const GET_USERS = 'GET_USERS'
const GET_USER = 'GET_USER'
const GET_ISAUTH = 'GET_ISAUTH'
const SET_USER = 'SET_USER'
const SET_ISAUTH = 'SET_ISAUTH'
const SET_IS_LOADING = 'SET_IS_LOADING'
const SET_NEW_TASK = 'SET_NEW_TASK'
const SET_TASKS_FOR_ADMIN = 'SET_TASKS_FOR_ADMIN'
const SET_NEW_TASK_LIST = 'SET_NEW_TASK_LIST'
const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'
const CHANGE_TASK = 'CHANGE_TASK'


export {
    SET_LIST, GET_USERS, GET_USER, GET_ISAUTH, SET_USER, SET_ISAUTH,
    SET_IS_LOADING, GET_LIST, SET_NEW_TASK, SET_TASKS_FOR_ADMIN, SET_NEW_TASK_LIST,
    SET_CURRENT_PAGE, CHANGE_TASK
}